server:
  port: 9003
spring:
  application:
    name: business-service
  datasource:
    url: jdbc:mysql://47.100.178.53:3306/weiyun
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

mybatis:
  type-aliases-package: com.wy.pojo


eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:10086/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
