server:
  port: 9002
spring:
  application:
    name: user-service
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://47.100.178.53:3306/weiyun
    username: root
    password: 123456
  redis:
    host: 47.100.178.53
  rabbitmq:
    host: 47.100.178.53
    username: weiyun
    password: weiyun
    virtual-host: /weiyun
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 210000ms
        multiplier: 2
    publisher-confirms: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

mybatis:
  type-aliases-package: com.wy.user.pojo
