server:
  port: 9004
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 47.100.178.53
    username: weiyun
    password: weiyun
    virtual-host: /weiyun
wy:
  sms:
    accessKeyId: LTAI4FibdDj17mSxG1gmi87K # 你自己的accessKeyId
    accessKeySecret: 3Y1rkKpjKiykhlVyqhWaLhMQRApk2s  # 你自己的AccessKeySecret
    signName: 微云智能管理平台 # 签名名称
    verifyCodeTemplate: SMS_177549309 # 模板名称