server:
  port: 9004
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 47.100.178.53
    username: weiyun
    password: weiyun
    virtual-host: /weiyun
wy:
  sms:
    accessKeyId: LTAI4FsEJo7uoqF26GQSLRb4 # 你自己的accessKeyId
    accessKeySecret: j19ULHZXtfnZvjrl2iw6zMmzhHc8eH  # 你自己的AccessKeySecret
    signName: 微云智能管理平台 # 签名名称
    verifyCodeTemplate: SMS_177549309 # 模板名称