server:
  port: 8085
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.157.200
    username: wlkg
    password: 123456
    virtual-host: /wlkg
wy:
  sms:
    accessKeyId: LTAI4FibdDj17mSxG1gmi87K # 你自己的accessKeyId
    accessKeySecret: 3Y1rkKpjKiykhlVyqhWaLhMQRApk2s  # 你自己的AccessKeySecret
    signName: 危运三人管理中心 # 签名名称
    verifyCodeTemplate: 危运短信验证码 # 模板名称