server:
  port: 10010


spring:
  application:
    name: zuul-server


eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:10086/eureka/
#actuator设置
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点,默认是info和health
  endpoint:
    health:
      show-details: always #默认是never

#网关配置....
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 2000
  routes:
    admin-service: /admin/**


ribbon:
  ConnectTimeout: 2000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长：10000ms
